# Generated by Django 5.0.8 on 2025-09-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalvocabulary',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical موضوع', 'verbose_name_plural': 'historical موضوعات'},
        ),
        migrations.AlterModelOptions(
            name='historicalvocabularyterm',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical واژه', 'verbose_name_plural': 'historical واژگان'},
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'ordering': ['name'], 'verbose_name': 'موضوع', 'verbose_name_plural': 'موضوعات'},
        ),
        migrations.AlterModelOptions(
            name='vocabularyterm',
            options={'ordering': ['vocabulary__name', 'term'], 'verbose_name': 'واژه', 'verbose_name_plural': 'واژگان'},
        ),
    ]
