# Generated by Django 5.0.8 on 2025-09-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_comprehensive_vocabulary_changes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallanguage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical زبان', 'verbose_name_plural': 'historical زبان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='historicalscheme',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical طرح کلی', 'verbose_name_plural': 'historical طرح\u200cهای کلی'},
        ),
        migrations.AddField(
            model_name='historicalscheme',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='historicallanguage',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalscheme',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
