# Generated by Django 5.0.8 on 2025-09-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_alter_historicallanguage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvocabulary',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='description',
        ),
    ]
