# Generated by Django 5.0.8 on 2025-09-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_remove_historicalvocabulary_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscheme',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='description',
        ),
    ]
