# Generated by Django 5.0.8 on 2025-08-30 21:36

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('document', 'سند'), ('unit', 'واحد'), ('qa', 'پرسش و پاسخ'), ('vocabulary', 'واژگان'), ('authority', 'مرجع'), ('jurisdiction', 'حوزه قضایی')], max_length=20, verbose_name='نوع کار')),
                ('target_id', models.UUIDField(verbose_name='شناسه هدف')),
                ('payload_preview', models.JSONField(default=dict, verbose_name='پیش\u200cنمایش محتوا')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('success', 'موفق'), ('error', 'خطا')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('last_error', models.TextField(blank=True, verbose_name='آخرین خطا')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش مجدد')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='حداکثر تلاش مجدد')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تلاش بعدی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
            ],
            options={
                'verbose_name': 'کار همگام\u200cسازی',
                'verbose_name_plural': 'کارهای همگام\u200cسازی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSyncJob',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('job_type', models.CharField(choices=[('document', 'سند'), ('unit', 'واحد'), ('qa', 'پرسش و پاسخ'), ('vocabulary', 'واژگان'), ('authority', 'مرجع'), ('jurisdiction', 'حوزه قضایی')], max_length=20, verbose_name='نوع کار')),
                ('target_id', models.UUIDField(verbose_name='شناسه هدف')),
                ('payload_preview', models.JSONField(default=dict, verbose_name='پیش\u200cنمایش محتوا')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('success', 'موفق'), ('error', 'خطا')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('last_error', models.TextField(blank=True, verbose_name='آخرین خطا')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش مجدد')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='حداکثر تلاش مجدد')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تلاش بعدی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical کار همگام\u200cسازی',
                'verbose_name_plural': 'historical کارهای همگام\u200cسازی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
