# Generated by Django 5.0.8 on 2025-09-01 17:43

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentExpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='fa', max_length=10, verbose_name='زبان')),
                ('consolidation_level', models.CharField(blank=True, max_length=50, verbose_name='سطح تلفیق')),
                ('expression_date', models.DateField(verbose_name='تاریخ بیان')),
                ('eli_uri_expr', models.URLField(blank=True, verbose_name='ELI URI بیان')),
            ],
            options={
                'verbose_name': 'بیان حقوقی',
                'verbose_name_plural': 'بیان\u200cهای حقوقی',
            },
        ),
        migrations.CreateModel(
            name='HistoricalInstrumentWork',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title_official', models.CharField(max_length=500, verbose_name='عنوان رسمی')),
                ('doc_type', models.CharField(choices=[('law', 'قانون'), ('bylaw', 'آیین\u200cنامه'), ('circular', 'بخشنامه'), ('ruling', 'رأی'), ('decree', 'مصوبه'), ('regulation', 'مقررات'), ('instruction', 'دستورالعمل'), ('other', 'سایر')], default='law', max_length=20, verbose_name='نوع سند')),
                ('eli_uri_work', models.URLField(blank=True, verbose_name='ELI URI اثر')),
                ('urn_lex', models.CharField(blank=True, max_length=200, verbose_name='URN LEX')),
                ('local_slug', models.SlugField(max_length=100, verbose_name='شناسه محلی')),
                ('primary_language', models.CharField(default='fa', max_length=10, verbose_name='زبان اصلی')),
                ('subject_summary', models.TextField(blank=True, verbose_name='خلاصه موضوع')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('authority', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.issuingauthority', verbose_name='مرجع صادرکننده')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('jurisdiction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.jurisdiction', verbose_name='حوزه قضایی')),
            ],
            options={
                'verbose_name': 'historical اثر حقوقی',
                'verbose_name_plural': 'historical آثار حقوقی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInstrumentManifestation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('publication_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('official_gazette_name', models.CharField(blank=True, max_length=200, verbose_name='نام روزنامه رسمی')),
                ('gazette_issue_no', models.CharField(blank=True, max_length=50, verbose_name='شماره نشریه')),
                ('page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='صفحه شروع')),
                ('page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='صفحه پایان')),
                ('source_url', models.URLField(blank=True, verbose_name='URL منبع')),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='چکسام SHA256')),
                ('eli_uri_manifestation', models.URLField(blank=True, verbose_name='ELI URI تجلی')),
                ('in_force_from', models.DateField(blank=True, null=True, verbose_name='اجرا از تاریخ')),
                ('in_force_to', models.DateField(blank=True, null=True, verbose_name='اجرا تا تاریخ')),
                ('repeal_status', models.CharField(blank=True, max_length=50, verbose_name='وضعیت لغو')),
                ('retrieval_date', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بازیابی')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expr', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.instrumentexpression', verbose_name='بیان')),
            ],
            options={
                'verbose_name': 'historical تجلی حقوقی',
                'verbose_name_plural': 'historical تجلی\u200cهای حقوقی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InstrumentManifestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('official_gazette_name', models.CharField(blank=True, max_length=200, verbose_name='نام روزنامه رسمی')),
                ('gazette_issue_no', models.CharField(blank=True, max_length=50, verbose_name='شماره نشریه')),
                ('page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='صفحه شروع')),
                ('page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='صفحه پایان')),
                ('source_url', models.URLField(blank=True, verbose_name='URL منبع')),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, unique=True, verbose_name='چکسام SHA256')),
                ('eli_uri_manifestation', models.URLField(blank=True, verbose_name='ELI URI تجلی')),
                ('in_force_from', models.DateField(blank=True, null=True, verbose_name='اجرا از تاریخ')),
                ('in_force_to', models.DateField(blank=True, null=True, verbose_name='اجرا تا تاریخ')),
                ('repeal_status', models.CharField(blank=True, max_length=50, verbose_name='وضعیت لغو')),
                ('retrieval_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازیابی')),
                ('expr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='documents.instrumentexpression', verbose_name='بیان')),
            ],
            options={
                'verbose_name': 'تجلی حقوقی',
                'verbose_name_plural': 'تجلی\u200cهای حقوقی',
            },
        ),
        migrations.CreateModel(
            name='InstrumentWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_official', models.CharField(max_length=500, verbose_name='عنوان رسمی')),
                ('doc_type', models.CharField(choices=[('law', 'قانون'), ('bylaw', 'آیین\u200cنامه'), ('circular', 'بخشنامه'), ('ruling', 'رأی'), ('decree', 'مصوبه'), ('regulation', 'مقررات'), ('instruction', 'دستورالعمل'), ('other', 'سایر')], default='law', max_length=20, verbose_name='نوع سند')),
                ('eli_uri_work', models.URLField(blank=True, verbose_name='ELI URI اثر')),
                ('urn_lex', models.CharField(blank=True, max_length=200, verbose_name='URN LEX')),
                ('local_slug', models.SlugField(max_length=100, unique=True, verbose_name='شناسه محلی')),
                ('primary_language', models.CharField(default='fa', max_length=10, verbose_name='زبان اصلی')),
                ('subject_summary', models.TextField(blank=True, verbose_name='خلاصه موضوع')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_works', to='masterdata.issuingauthority', verbose_name='مرجع صادرکننده')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_works', to='masterdata.jurisdiction', verbose_name='حوزه قضایی')),
            ],
            options={
                'verbose_name': 'اثر حقوقی',
                'verbose_name_plural': 'آثار حقوقی',
            },
        ),
        migrations.AddField(
            model_name='instrumentexpression',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='documents.instrumentwork', verbose_name='اثر'),
        ),
        migrations.CreateModel(
            name='HistoricalInstrumentExpression',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('language', models.CharField(default='fa', max_length=10, verbose_name='زبان')),
                ('consolidation_level', models.CharField(blank=True, max_length=50, verbose_name='سطح تلفیق')),
                ('expression_date', models.DateField(verbose_name='تاریخ بیان')),
                ('eli_uri_expr', models.URLField(blank=True, verbose_name='ELI URI بیان')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.instrumentwork', verbose_name='اثر')),
            ],
            options={
                'verbose_name': 'historical بیان حقوقی',
                'verbose_name_plural': 'historical بیان\u200cهای حقوقی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='instrumentmanifestation',
            constraint=models.CheckConstraint(check=models.Q(('in_force_to__gte', models.F('in_force_from')), ('in_force_to__isnull', True), _connector='OR'), name='valid_in_force_period'),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentexpression',
            unique_together={('work', 'language', 'consolidation_level', 'expression_date')},
        ),
    ]
