# Generated by Django 5.0.8 on 2025-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstrumentwork',
            name='local_slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='شناسه محلی'),
        ),
        migrations.AlterField(
            model_name='instrumentwork',
            name='local_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='شناسه محلی'),
        ),
    ]
