# Generated by Django 5.0.8 on 2025-09-01 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_instrumentexpression_historicalinstrumentwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallegalunit',
            name='eli_fragment',
            field=models.CharField(blank=True, max_length=200, verbose_name='ELI Fragment'),
        ),
        migrations.AddField(
            model_name='historicallegalunit',
            name='expr',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.instrumentexpression', verbose_name='بیان'),
        ),
        migrations.AddField(
            model_name='historicallegalunit',
            name='manifestation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.instrumentmanifestation', verbose_name='تجلی'),
        ),
        migrations.AddField(
            model_name='historicallegalunit',
            name='text_plain',
            field=models.TextField(blank=True, verbose_name='متن ساده'),
        ),
        migrations.AddField(
            model_name='historicallegalunit',
            name='work',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.instrumentwork', verbose_name='اثر'),
        ),
        migrations.AddField(
            model_name='historicallegalunit',
            name='xml_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='XML ID'),
        ),
        migrations.AddField(
            model_name='legalunit',
            name='eli_fragment',
            field=models.CharField(blank=True, max_length=200, verbose_name='ELI Fragment'),
        ),
        migrations.AddField(
            model_name='legalunit',
            name='expr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='documents.instrumentexpression', verbose_name='بیان'),
        ),
        migrations.AddField(
            model_name='legalunit',
            name='manifestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='documents.instrumentmanifestation', verbose_name='تجلی'),
        ),
        migrations.AddField(
            model_name='legalunit',
            name='text_plain',
            field=models.TextField(blank=True, verbose_name='متن ساده'),
        ),
        migrations.AddField(
            model_name='legalunit',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='documents.instrumentwork', verbose_name='اثر'),
        ),
        migrations.AddField(
            model_name='legalunit',
            name='xml_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='XML ID'),
        ),
        migrations.AlterField(
            model_name='legalunit',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='documents.legaldocument', verbose_name='سند'),
        ),
        migrations.AddConstraint(
            model_name='legalunit',
            constraint=models.CheckConstraint(check=models.Q(('document__isnull', False), ('work__isnull', False), _connector='OR'), name='legalunit_has_document_or_work'),
        ),
    ]
