# Generated by Django 5.0.8 on 2025-09-06 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_historicalinstrumentwork_local_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpinpointcitation',
            name='from_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.legalunit', verbose_name='سند مبدأ'),
        ),
        migrations.AlterField(
            model_name='historicalpinpointcitation',
            name='to_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.legalunit', verbose_name='سند اشاره شده'),
        ),
        migrations.AlterField(
            model_name='pinpointcitation',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_citations', to='documents.legalunit', verbose_name='سند مبدأ'),
        ),
        migrations.AlterField(
            model_name='pinpointcitation',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_citations', to='documents.legalunit', verbose_name='سند اشاره شده'),
        ),
    ]
