# Generated by Django 5.0.8 on 2025-09-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_historicalpinpointcitation_from_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpinpointcitation',
            name='end_offset',
        ),
        migrations.RemoveField(
            model_name='historicalpinpointcitation',
            name='start_offset',
        ),
        migrations.RemoveField(
            model_name='pinpointcitation',
            name='end_offset',
        ),
        migrations.RemoveField(
            model_name='pinpointcitation',
            name='start_offset',
        ),
    ]
