# Generated by Django 5.0.8 on 2025-09-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_historicalpinpointcitation_end_offset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalunittag',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalunittag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicalunittag',
            name='tagged_by',
        ),
        migrations.RemoveField(
            model_name='historicalunittag',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='historicalworktag',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalworktag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicalworktag',
            name='tagged_by',
        ),
        migrations.RemoveField(
            model_name='historicalworktag',
            name='work',
        ),
        migrations.RemoveField(
            model_name='unittag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='worktag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='unittag',
            name='tagged_by',
        ),
        migrations.RemoveField(
            model_name='unittag',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='worktag',
            name='tagged_by',
        ),
        migrations.RemoveField(
            model_name='worktag',
            name='work',
        ),
        migrations.DeleteModel(
            name='HistoricalTag',
        ),
        migrations.DeleteModel(
            name='HistoricalUnitTag',
        ),
        migrations.DeleteModel(
            name='HistoricalWorkTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UnitTag',
        ),
        migrations.DeleteModel(
            name='WorkTag',
        ),
    ]
