# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('documents', '0005_remove_historicalunittag_history_user_and_more'),
    ]

    operations = [
        # Remove text_plain field from LegalUnit
        migrations.RemoveField(
            model_name='legalunit',
            name='text_plain',
        ),
        migrations.RemoveField(
            model_name='historicallegalunit',
            name='text_plain',
        ),
        
        # Create LegalUnitVocabularyTerm model
        migrations.CreateModel(
            name='LegalUnitVocabularyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('weight', models.PositiveSmallIntegerField(default=5, help_text='وزن ارتباط (1 تا 10)', verbose_name='وزن')),
                ('legal_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_vocabulary_terms', to='documents.legalunit', verbose_name='جزء سند')),
                ('vocabulary_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_vocabulary_terms', to='masterdata.vocabularyterm', verbose_name='واژه')),
            ],
            options={
                'verbose_name': 'برچسب جزء سند',
                'verbose_name_plural': 'برچسب‌های اجزاء سند',
            },
        ),
        
        # Create HistoricalLegalUnitVocabularyTerm model
        migrations.CreateModel(
            name='HistoricalLegalUnitVocabularyTerm',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('weight', models.PositiveSmallIntegerField(default=5, help_text='وزن ارتباط (1 تا 10)', verbose_name='وزن')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.user')),
                ('legal_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.legalunit', verbose_name='جزء سند')),
                ('vocabulary_term', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.vocabularyterm', verbose_name='واژه')),
            ],
            options={
                'verbose_name': 'historical برچسب جزء سند',
                'verbose_name_plural': 'historical برچسب‌های اجزاء سند',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        
        # Add many-to-many field to LegalUnit
        migrations.AddField(
            model_name='legalunit',
            name='vocabulary_terms',
            field=models.ManyToManyField(blank=True, related_name='legal_units', through='documents.LegalUnitVocabularyTerm', to='masterdata.vocabularyterm', verbose_name='برچسب‌ها'),
        ),
        
        # Add unique constraint
        migrations.AddConstraint(
            model_name='legalunitvocabularyterm',
            constraint=models.UniqueConstraint(fields=('legal_unit', 'vocabulary_term'), name='unique_legal_unit_vocabulary_term'),
        ),
    ]
