# Generated by Django 5.0.8 on 2025-09-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_historicalinstrumentwork_eli_uri_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstrumentwork',
            name='eli_uri_work',
            field=models.URLField(blank=True, help_text='https://domain/country/type/year/number<br>مثال: https://laws.example.ir/ir/act/2020/123', verbose_name='ELI URI اثر'),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentwork',
            name='urn_lex',
            field=models.CharField(blank=True, help_text='ir:authority:doc_type:yyyy-mm-dd:number<br>مثال: ir:majlis:law:2020-06-01:123', max_length=200, verbose_name='URN LEX'),
        ),
        migrations.AlterField(
            model_name='instrumentwork',
            name='eli_uri_work',
            field=models.URLField(blank=True, help_text='https://domain/country/type/year/number<br>مثال: https://laws.example.ir/ir/act/2020/123', verbose_name='ELI URI اثر'),
        ),
        migrations.AlterField(
            model_name='instrumentwork',
            name='urn_lex',
            field=models.CharField(blank=True, help_text='ir:authority:doc_type:yyyy-mm-dd:number<br>مثال: ir:majlis:law:2020-06-01:123', max_length=200, verbose_name='URN LEX'),
        ),
    ]
