# Generated by Django 5.0.8 on 2025-09-06 13:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_legalunit_text_plain_and_more'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='legalunitvocabularyterm',
            name='unique_legal_unit_vocabulary_term',
        ),
        migrations.AlterField(
            model_name='historicallegalunitvocabularyterm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicallegalunitvocabularyterm',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicallegalunitvocabularyterm',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='legalunitvocabularyterm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='legalunitvocabularyterm',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legalunitvocabularyterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='legalunitvocabularyterm',
            unique_together={('legal_unit', 'vocabulary_term')},
        ),
    ]
