# Generated by Django 5.0.8 on 2025-09-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_instrumentexpression_consolidation_level_and_more'),
        ('documents', '0007_alter_historicalinstrumentwork_eli_uri_work_and_more'),
    ]

    operations = [
    ]
