# Generated by Django 5.0.8 on 2025-09-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_instrumentexpression_consolidation_level_and_more'),
        ('documents', '0008_merge_20250905_0548'),
    ]

    operations = [
    ]
