# Generated by Django 5.0.8 on 2025-09-05 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_merge_20250905_0655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinstrumentexpression',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical تعریف نسخه سند', 'verbose_name_plural': 'historical تعریف نسخه سند'},
        ),
        migrations.AlterModelOptions(
            name='historicalinstrumentmanifestation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical تعریف انتشار سند', 'verbose_name_plural': 'historical تعریف انتشار سند'},
        ),
        migrations.AlterModelOptions(
            name='historicalinstrumentwork',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical تعریف سند حقوقی', 'verbose_name_plural': 'historical تعریف سند حقوقی'},
        ),
        migrations.AlterModelOptions(
            name='instrumentexpression',
            options={'verbose_name': 'تعریف نسخه سند', 'verbose_name_plural': 'تعریف نسخه سند'},
        ),
        migrations.AlterModelOptions(
            name='instrumentmanifestation',
            options={'verbose_name': 'تعریف انتشار سند', 'verbose_name_plural': 'تعریف انتشار سند'},
        ),
        migrations.AlterModelOptions(
            name='instrumentwork',
            options={'verbose_name': 'تعریف سند حقوقی', 'verbose_name_plural': 'تعریف سند حقوقی'},
        ),
        migrations.RemoveField(
            model_name='historicalinstrumentmanifestation',
            name='eli_uri_manifestation',
        ),
        migrations.RemoveField(
            model_name='historicalinstrumentmanifestation',
            name='page_end',
        ),
        migrations.RemoveField(
            model_name='instrumentmanifestation',
            name='eli_uri_manifestation',
        ),
        migrations.RemoveField(
            model_name='instrumentmanifestation',
            name='page_end',
        ),
        migrations.AlterField(
            model_name='historicalinstrumentexpression',
            name='expression_date',
            field=models.DateField(verbose_name='تاریخ نسخه'),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentexpression',
            name='work',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.instrumentwork', verbose_name='سند حقوقی'),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentmanifestation',
            name='expr',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.instrumentexpression', verbose_name='نسخه سند'),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentmanifestation',
            name='gazette_issue_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره نامه'),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentmanifestation',
            name='in_force_to',
            field=models.DateField(blank=True, help_text='در صورتی که وضعیت سند "لغو یا منسوخ شده" باشد، این فیلد الزامی است.', null=True, verbose_name='اجرا تا تاریخ'),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentmanifestation',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='صفحه شروع-پایان'),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentmanifestation',
            name='repeal_status',
            field=models.CharField(choices=[('in_force', 'جاری و لازم الاجرا'), ('repealed', 'لغو یا منسوخ شده')], default='in_force', max_length=20, verbose_name='وضعیت سند'),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentmanifestation',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='ELI URI / URL منبع'),
        ),
        migrations.AlterField(
            model_name='instrumentexpression',
            name='expression_date',
            field=models.DateField(verbose_name='تاریخ نسخه'),
        ),
        migrations.AlterField(
            model_name='instrumentexpression',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='documents.instrumentwork', verbose_name='سند حقوقی'),
        ),
        migrations.AlterField(
            model_name='instrumentmanifestation',
            name='expr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations', to='documents.instrumentexpression', verbose_name='نسخه سند'),
        ),
        migrations.AlterField(
            model_name='instrumentmanifestation',
            name='gazette_issue_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره نامه'),
        ),
        migrations.AlterField(
            model_name='instrumentmanifestation',
            name='in_force_to',
            field=models.DateField(blank=True, help_text='در صورتی که وضعیت سند "لغو یا منسوخ شده" باشد، این فیلد الزامی است.', null=True, verbose_name='اجرا تا تاریخ'),
        ),
        migrations.AlterField(
            model_name='instrumentmanifestation',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='صفحه شروع-پایان'),
        ),
        migrations.AlterField(
            model_name='instrumentmanifestation',
            name='repeal_status',
            field=models.CharField(choices=[('in_force', 'جاری و لازم الاجرا'), ('repealed', 'لغو یا منسوخ شده')], default='in_force', max_length=20, verbose_name='وضعیت سند'),
        ),
        migrations.AlterField(
            model_name='instrumentmanifestation',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='ELI URI / URL منبع'),
        ),
    ]
